-- AshisDigitalHub lead capture
create table if not exists public.lead_submissions (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name text not null,
  contact text not null,
  need text not null default 'Not sure yet',
  message text not null default '',
  source text not null default 'ashisdigitalhub.com consultation form',
  landing_page text not null default '/',
  user_agent text,
  notification_status text not null default 'pending' check (notification_status in ('pending', 'sent', 'failed')),
  notified_at timestamptz
);

alter table public.lead_submissions enable row level security;

-- The server uses the secret SUPABASE_KEY and writes through the REST API.
-- Do not expose that key in browser JavaScript. No public read policy is created.
create index if not exists lead_submissions_created_at_idx on public.lead_submissions (created_at desc);
create index if not exists lead_submissions_notification_status_idx on public.lead_submissions (notification_status);

-- Optional: create a Supabase Database Webhook named `lead-gmail-notification`
-- on INSERT to public.lead_submissions. Point it to the deployed notification
-- function documented in supabase/README.md, then set notification_status to sent.
